### ISSUE TITLE
The coefficient in deltaenergy.m

### ISSUE THREAD

**Issue by Cam1110** [EnthalpyBill/2D-Ising-Model-Matlab#1]
Deltaenergy.m Line 3
        out1 = **4** * J * grid(i,j) * (left(i,j,grid) + right(i,j,grid) + up(i,j,grid) + down(i,j,grid));
Why the coefficient is 4 instead of 2?

**Comment by ybillchen** [comment]
Hello,

Thanks for the nice catch! Yes, there is a mistake, but not this one. When calculating the total energy, I simply sum up all unit energies. Therefore, each pair of neighbors is counted twice. This makes the total energy twice larger. So that I use the coefficient of 4 when calculating the energy change. You can understand this as replacing J with 2J.
